server {
    listen 80;

    root /usr/share/nginx/html;

    location / {
        types { }
        default_type text/calendar;
        charset utf-8;

        add_header Cache-Control "no-cache, must-revalidate";
        add_header Access-Control-Allow-Origin "*";
    }
}